### PR TITLE
Get Rbac permissions

### PR DESCRIPTION
**Pull request by tahmidefaz**
Jira: [Here](https://projects.engineering.redhat.com/browse/RHCLOUD-3683)

Let me know what needs changing here! Also, not sure if I did the tests right! :smile:

### CODE REVIEW

**Comment by tahmidefaz** [comment]
@karelhala I wasn't aware of the rbac api. Thank you for pointing it out! I just tweaked your suggestion a little bit, so that it fetches the correct count for permissions.

**Comment by tahmidefaz** [comment]
> Looking good! I checked it locally and it returns correct number of permissions and such. Really nice!

Thanks for checking it locally!

**Comment by karelhala** [comment]
@PanSpagetka was working on some self clearing localstorage enhancements.

**Comment by tahmidefaz** [comment]
I tried quite a few things regarding the async tests without any luck. I will give it another try tomorrow. Let me know if you have any suggestions @karelhala @ryelo

**Comment by tahmidefaz** [comment]
Just added the test. Let me know if it needs to be improved.

**Pull request merged**
