### PR TITLE
[RHCLOUD-31132] Make sure dev env's use staticConfig instead of operator-generated

### PR DESCRIPTION
**Pull request by aneelac22**

### CODE REVIEW

**Comment by Hyperkid123** [comment]
Any particular reason for this? Ideally, we distinguish between envs via configuration, not in code.

**Comment by aneelac22** [comment]
> Any particular reason for this? Ideally, we distinguish between envs via configuration, not in code.

I was told there is no dev deployment and it uses stage deployment for frontend and prod for backend and no way to change config in Operator because of that

**Comment by Hyperkid123** [comment]
Is there a conversation or a ticket or something I can read?

**Comment by aneelac22** [comment]
> Is there a conversation or a ticket or something I can read?

https://redhat-internal.slack.com/archives/C05KTHJU4R4/p1708617749235119?thread_ts=1708540844.466109&cid=C05KTHJU4R4

**Review by fhlavac — APPROVED** [review]

**Pull request closed without merging**
