### PR TITLE
Fix navigation after refactoring

### PR DESCRIPTION
**Pull request by karelhala**

### CODE REVIEW

**Review by Hyperkid123 — COMMENTED** [review]
@karelhala  I see that the nav is s still generating incorrect URL:

Screenshot from 2020-09-21 17-23-17

**Review by Hyperkid123 — COMMENTED** [review]
@karelhala I am still getting redirected back to the "top level" app. See the gif. The URL is correct though. Did the navigation API change at all? Maybe we need to fix it inside the app itself.
approval redirect

**Comment by karelhala** [comment]
@Hyperkid123 I've tried it with app deployed on cloud instead of locally and it works as expected
animation

However with local catalog running it forced ridirect to approval, I think it's caused by the app running locally

**Comment by Hyperkid123** [comment]
@karelhala yeah that is probably it.

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
