### PR TITLE
Update AAP filter usage

### PR DESCRIPTION
**Pull request by kruai**
The current AAP filter does not work, as it will only fetch hosts which have _all_ of ansible's child fields populated
On the API side, we're adding the ability to filter on whether a parent field has any child field with a value. This PR should not be merged until the API change is ready.

[This PR](https://github.com/RedHatInsights/insights-inventory-frontend/pull/1502) updates the implementation on the HBI front-end.

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@kruai I have changed the PR to draft so we don't accidentally hit the button.

**Comment by kruai** [comment]
@karelhala @Hyperkid123 This is now ready for review! The API PR got merged and is now live in Stage.

**Review by ryandillinfelton — APPROVED** [review]

**Comment by Hyperkid123** [comment]
@kruai when can we expect it in production?

**Comment by kruai** [comment]
> @kruai when can we expect it in production?

We're going to try to promote the HBI API change to Prod on Monday.

**Comment by Hyperkid123** [comment]
> > @kruai when can we expect it in production?
> 
> We're going to try to promote the HBI API change to Prod on Monday.

@kruai Cool, please ping me on slack so we can add this commit to prod as well.

**Pull request merged**
