### PR TITLE
add repositories app to "All Services"

### PR DESCRIPTION
**Pull request by jlsherrill**
and reorder deploy to be alphabetical

### CODE REVIEW

**Comment by jlsherrill** [comment]
as part of this it was requested to correctly sort the deploy group alphabetically

**Comment by Hyperkid123** [comment]
@jlsherrill is there a jira ticket?

**Comment by jlsherrill** [comment]
@Hyperkid123 there isn't, I'm happy to open one, would it be to RHCLOUD?  On slack someone mentioned i could just open a Pr, but happy to file a ticket :)

**Comment by jlsherrill** [comment]
oh i see that this list has moved... where has it moved to?

**Comment by Hyperkid123** [comment]
@jlsherrill yes please open a new ticket and tag Kendra Marchant so the UX knows about the change.

And yeah the content was moved to a variable because of some features that are required.

**Review by epwinchell — APPROVED** [review]
@jlsherrill Thank you. These should all be alphabetical.

**Pull request merged**
