### PR TITLE
New Nav styling updates & fixes

### PR DESCRIPTION
**Pull request by epwinchell**
Jira: https://issues.redhat.com/browse/RHCLOUD-24903

- Remove AllService icons
- Add missing Favoriting Empty State
- Add missing Favoriting page text
- Add "All Services" favoriting icon behavior to nav panels (move styling to `chrome.scss` to be shared by both pages)
- Fix invisible ExernalLink icons
- Set min-height on panel to avoid jumping while loading

Screenshot 2023-03-28 at 3 26 05 PM
Screenshot 2023-03-28 at 3 26 43 PM
Screenshot 2023-03-28 at 3 27 21 PM

### CODE REVIEW

**Comment by epwinchell** [comment]
@Hyperkid123 This still shows up occasionally in place of empty state
Screenshot 2023-03-28 at 3 29 20 PM

**Comment by Hyperkid123** [comment]
@epwinchell I have found a strange edge case. When you rebase on master, then open the dropdown and hover over the clusters time, it will throw off the styling. I think OpenShift APP has some unscoped CSS included in their chunks.

It will cause this issue. The spacing gets weird and also all services link on the bottom left just jumps out of the container. Can you take a look at this edge case?
screenshot-stage foo redhat com_1337-2023 03 29-11_48_20

**Comment by Hyperkid123** [comment]
> @Hyperkid123 When you first remove a service, Empty State appears and sticks around for a while, then seems to get replaced by this

I'll take a look at the state values.

**Comment by epwinchell** [comment]
> Can you take a look at this edge case?
@Hyperkid123 Fixed after conflicts resolved

Screenshot 2023-03-29 at 10 19 30 AM

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
