### PR TITLE
Move info from Footer to About page

### PR DESCRIPTION
**Pull request by kruai**
For this merge, I made the following changes:

- Added a small fix that re-enabled version number updates
- Changed build_number to src_hash by request
- Added info from the footer into the About page (needs styling though?)
- Removed contents from footer.pug

### CODE REVIEW

**Comment by ryelo** [comment]
@kruai Do you want me to edit the styling for this? Or we can wait until merge and I can open up another PR.

**Comment by kruai** [comment]
Could you actually make the changes for this PR? I'd really like to see how you go about styling it, because I've barely done any front-end design before.

**Comment by ryelo** [comment]
@kruai sure thing! I'll take a look at this soon.

**Comment by kruai** [comment]
@ryelo If styling it will take a while, can we actually do it as a separate PR? I'd like to make sure things look OK on CI so I can quickly fix anything that breaks. I can always look at the styling changes you make on the new PR :)

**Comment by ryelo** [comment]
@kruai For sure! I'll probably work on this when I am back in Raleigh

**Comment by kruai** [comment]
OK. Then can you or @karelhala please review or tell me what I need to change?

**Pull request merged**
