### PR TITLE
Rename Advisor to Insights

### PR DESCRIPTION
**Pull request by AllenBW**
@Robcwilliams @karelhala

### CODE REVIEW

**Comment by AllenBW** [comment]
Yeah sure thing! 👌

**Comment by AllenBW** [comment]
@ryelo looks like the name was changed since this was opened, but not the about page... 🤔

**Comment by karelhala** [comment]
Sorry for the late response @AllenBW.

**Comment by AllenBW** [comment]
No worries!! 🤗 🤗

**Pull request merged**
