### PR TITLE
Update prod-stable to newest version

### PR DESCRIPTION
**Pull request by karelhala**

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@karelhala I think this will introduce the menu text alignment bug right?

**Comment by karelhala** [comment]
@Hyperkid123 yup. You should cherry pick that fix to master-stable and open PR with it to be in all stable envs. We can merge this once that PR is in master-stable

**Comment by Hyperkid123** [comment]
@karelhala alright I'll do it in a bit.

**Comment by jiridostal** [comment]
Please postpone the release for tomorrow, Patch is having a demo today, so to overcome any issues.

**Pull request merged**
