### PR TITLE
Add email visibility function (#1432)

### PR DESCRIPTION
**Pull request by karelhala**
@ryelo this one also includes the `isHidden` function.

### CODE REVIEW

**Review by Hyperkid123 — APPROVED** [review]

**Comment by ryelo** [comment]
@karelhala Do you need to bring in the logic for the nav for `isHidden` here too?

**Comment by Hyperkid123** [comment]
@ryelo it's in the commit.

**Comment by ryelo** [comment]
I only see the addition to consts.js?

**Comment by Hyperkid123** [comment]
You are right.

**Comment by karelhala** [comment]
@ryelo aaah, you are right! Let me bring that one over as well.

**Comment by karelhala** [comment]
@ryelo updated! With both commits to hide items in expandable nav as well.

**Review by ryelo — APPROVED** [review]

**Pull request merged**
