### PR TITLE
Update itless stage SSO URL

### PR DESCRIPTION
**Pull request by florkbr**

### CODE REVIEW

**Comment by florkbr** [comment]
I don't believe the E2E failures are related to this change:
```
NonEntitledModal
    1) should render modal for ansible
    2) should render modal for insights
    ✓ should render modal for subscriptions (1828ms)
    ✓ should render modal for cost_management (1067ms)
    ✓ should not render modal for unknown entitlement (445ms)
    ✓ should clode modal if close button is clicked (157ms)
    ✓ should clode modal if "Not now" button is clicked (128ms)


  5 passing (12s)
  2 failing

  1) NonEntitledModal
       should render modal for ansible:
     AssertionError: Timed out retrying after 4000ms: expected '<img.chr-c-application-info__logo>' to be 'visible'

This element `<img.chr-c-application-info__logo>` is not visible because it has an effective width and height of: `0 x 76` pixels.
      at Context.<anonymous> (webpack://insights-chrome/./cypress/component/NotEntitledModal/NotEntitledModal.cy.tsx:24:35)
      at runnable.fn (http://localhost:8080/__cypress/runner/cypress_runner.js:138756:19)
      at callFn (http://localhost:8080/__cypress/runner/cypress_runner.js:157405:21)
      at Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:157392:7)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:163204:30)
      at PassThroughHandlerContext.finallyHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:4072:23)
      at PassThroughHandlerContext.tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)

  2) NonEntitledModal
       should render modal for insights:
     AssertionError: Timed out retrying after 4000ms: expected '<img.chr-c-application-info__logo>' to be 'visible'

This element `<img.chr-c-application-info__logo>` is not visible because it has an effective width and height of: `0 x 76` pixels.
      at Context.<anonymous> (webpack://insights-chrome/./cypress/component/NotEntitledModal/NotEntitledModal.cy.tsx:24:35)
      at runnable.fn (http://localhost:8080/__cypress/runner/cypress_runner.js:138756:19)
      at callFn (http://localhost:8080/__cypress/runner/cypress_runner.js:157405:21)
      at Runnable.run (http://localhost:8080/__cypress/runner/cypress_runner.js:157392:7)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:163204:30)
      at PassThroughHandlerContext.finallyHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:4072:23)
      at PassThroughHandlerContext.tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:1519:31)
```

**Review by coderbydesign — APPROVED** [review]
🌴

**Pull request merged**
