### PR TITLE
Add more Red Hat icons

### PR DESCRIPTION
**Pull request by rvsia**
Add icons for several Red Hat products from PnT portal. Requested by Sources UX.

No icon is overriden.

Screenshot from 2020-04-29 15-15-09
Screenshot from 2020-04-29 15-15-07
Screenshot from 2020-04-29 15-15-04

### CODE REVIEW

**Comment by rvsia** [comment]
cc @karelhala

**Comment by karelhala** [comment]
@ryelo any thoughts?

**Comment by ryelo** [comment]
Works for me! Let's add to https://github.com/RedHatInsights/frontend-assets too if you don't mind! Eventually we want to get all the static stuff out of chrome and into that repo

**Comment by rvsia** [comment]
@ryelo Okay! :+1:  I will also open a PR containing these icons + 'long' AWS there.

**Comment by ryelo** [comment]
@rvsia Any objections to killing this PR since it's merged in frontend-assets?

**Comment by rvsia** [comment]
@ryelo ☠️

**Pull request closed without merging**
