### PR TITLE
Add a copy button to the about modal

### PR DESCRIPTION
**Pull request by ryelo**
~Patternfly alerts don't render on top of modals, so i'm going to inline them 😄~

This is actually the PF spec for alerts in modals

On Load:
Screen Shot 2019-06-11 at 2 55 17 PM

On hover:
Screen Shot 2019-06-11 at 2 55 23 PM

On successful copy:
Screen Shot 2019-06-12 at 11 11 18 AM

Will output:
```
{
  "Username": "rhn-insights-rlong",
  "CurrentApp": "Landing",
  "ApplicationPath": "/",
  "apps": [
    {
      "name": "Chrome",
      "path": "apps/chrome/app.info.json"
    },
    {
      "name": "Dashboard",
      "path": "apps/dashboard/app.info.json",
      "version": "be8c41a4f1a812e064897dfbf34ef94ab1b02f42"
    },
    {
      "name": "Inventory",
      "path": "apps/inventory/app.info.json",
      "version": "8c6757740cb36a26da6e36820cc8936dbb633b33"
    },
    {
      "name": "Remediations",
      "path": "apps/remediations/app.info.json",
      "version": "84681c6bec6d888ba2dbca74871be340e06ac285"
    },
    {
      "name": "Vulnerability",
      "path": "apps/vulnerability/app.info.json",
      "version": "587b8d07c01a20a75af2dfd4146c438dd8a39207"
    },
    {
      "name": "Compliance",
      "path": "apps/compliance/app.info.json",
      "version": "d6aa513798317cfa699ed40d78f15789ca4a0ec7"
    },
    {
      "name": "Cost Management",
      "path": "apps/cost-management/app.info.json",
      "version": "579d2fd614b11a8a2bc1d6b848ce98661504b46b"
    },
    {
      "name": "Insights",
      "path": "apps/insights/app.info.json",
      "version": "31041e1173fae843836750099436fc26a52e0535"
    }
  ]
}
```

### CODE REVIEW

**Comment by ryelo** [comment]
Waiting on Kendra's ack

**Comment by ryelo** [comment]
@katierik Can I get an ack from you too?

**Comment by katierik** [comment]
The PF alert style seems overkill to me, but threw it over to some PF experts to see if they already thought about this too.

**Comment by katierik** [comment]
Two small notes:
1 - Add "Copy" as a label next to the copy icon
2 - The "copy" action has a general pattern in PF that I think we should follow. Essentially, instead of a big inline notification (as you have), just use the tooltip to convey the info. See here: https://www.patternfly.org/v4/documentation/react/components/clipboardcopy/#clipboard-copy 
In this case, only copy the tooltip interaction.

Holla @ me again if you want a mock or more details :)

**Comment by ryelo** [comment]
@katierik The original Acceptance Criteria sent by Kendra said not to have any Copy text and to just use the icon. Thoughts on this? Happy to change it though.

**Comment by ryelo** [comment]
@karelhala @kruai Should be good to go

**Pull request merged**
