### PR TITLE
[RHCLOUD-25771] Search bar overlaps other UI elements when "schmushed"

### PR DESCRIPTION
**Pull request by rsun19**
Working with @epwinchell 

~~Last thing to do is figure out how to center the Menu under the search bar. Sometimes, the menu doesn't center presumably because the component changes in between viewports.~~

### CODE REVIEW

**Review by epwinchell — APPROVED** [review]

**Comment by rsun19** [comment]
Sorry for the commit spam, just found a new bug and patched it. It should be good now

**Comment by Hyperkid123** [comment]
@rsun19 can you squash the commits into one, please?

**Comment by rsun19** [comment]
Spent most of today trying to fix a really annoying bug... I fixed it, and did loads of manual testing so I think that everything is fine now!

**Comment by rsun19** [comment]
I also don't know why it's failing a test

**Comment by Hyperkid123** [comment]
> I also don't know why it's failing a test

The failure is unrelated. The SSO page is hanging I've opened a PR with some adjustments. Will rebase this once its merged.

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
