### PR TITLE
[prod-beta] add repositories app to "All Services"

### PR DESCRIPTION
**Pull request by jlsherrill**
and reorder deploy to be alphabetical

Related to https://issues.redhat.com/browse/RHCLOUD-23787  and https://github.com/RedHatInsights/insights-chrome/pull/2229

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@jlsherrill can you please cherry-pick the commit from the linked PR. We do not want the commit history to diverge as it will create issues in future deployments.

https://github.com/RedHatInsights/insights-chrome/pull/2229/commits/0759a5a8356c56bf1bf8e3afc2887eedd8298670

**Comment by jlsherrill** [comment]
@Hyperkid123 i don't think i can cherry pick it cleanly because the file this touches was moved as part of 86a556f0f86530a89ad179dba5e592ca433b4ed0  and it doesn't appear that that commit has made prod-beta yet.  Any ideas when it will?

**Comment by Hyperkid123** [comment]
I see.

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
