### PR TITLE
Changes to combat Pendo visitor/account de-duplication issues

### PR DESCRIPTION
**Pull request by iphands**

### CODE REVIEW

**Comment by ryelo** [comment]
@iphands Do you want to just bring in the changes from #1090 into this one too?

**Comment by iphands** [comment]
@ryelo  Works for me.

**Comment by iphands** [comment]
@ryelo can you check the JWT fields I pull from, I didnt actually look at them to confirm.

**Comment by ryelo** [comment]
@iphands updated. Org id was missing the `.internal` and updated `accountID` to the better named `userID`

**Review by karelhala — APPROVED** [review]

**Comment by ryelo** [comment]
@Hyperkid123 Going to revert this for now. I don't think we wanted to merge it quite yet.

**Comment by ryelo** [comment]
Nevermind, we're just gonna do it 🚀

**Pull request merged**
