### PR TITLE
Update/page layout

### PR DESCRIPTION
**Pull request by mattnolting**
Adds pf components to chrome
- header
- sidebar
- main

### CODE REVIEW

**Comment by ryelo** [comment]
see: [Update Guide](https://gist.github.com/ryelo/23c554456c002b5dc813ccfea416a73f)

**Comment by Kinlaw** [comment]
can we get rid of the commented out code?

**Comment by ryelo** [comment]
Are we removing the footer?

**Comment by Kinlaw** [comment]
Once https://github.com/RedHatInsights/insights-frontend-components/pull/74 is ready I'm fine merging this.

**Pull request merged**
