### PR TITLE
Embed VA entrypoint

### PR DESCRIPTION
**Pull request by Hyperkid123**
Part of: https://issues.redhat.com/browse/RHCLOUD-31775, https://issues.redhat.com/browse/RHCLOUD-31653, https://issues.redhat.com/browse/RHCLOUD-31652

Waitin for pendo config to ide the badge on affected routes

### CODE REVIEW

**Comment by ryelo** [comment]
@Hyperkid123 Not sure if you want to update this PR to not include insights, but I've updated Pendo for everything else mentioned. I think we can go ahead and release it and then follow up when Insights is ready?

**Comment by Hyperkid123** [comment]
PR updated, we will release insights separetely

**Pull request merged**
