### PR TITLE
add logout redirect

### PR DESCRIPTION
**Pull request by ryelo**
This will redirect someone logging out to `/logout`.

It's not going to work entirely because there isn't a logout page ready to show, but you can see the redirect hit in the url.

When we log back into the page from `/logout`, we need to make sure to redirect them to `/` or else it's going to redirect them to `/logout` since that is where they came from.

### CODE REVIEW

**Comment by iphands** [comment]
@rlong @kruai this is safe to take off of onhold now right?

**Comment by rlong** [comment]
I think you may have the wrong person.




Cheers,


Richard Long




Get Outlook for Android







On Thu, May 2, 2019 at 10:46 PM +0100, "Ian Page Hands" <notifications@github.com> wrote:












@rlong @kruai this is safe to take off of onhold now right?

**Comment by ryelo** [comment]
Hahaha ^

@iphands it should be good as soon as: https://github.com/RedHatInsights/landing-page-frontend/pull/37 is merged

**Comment by ryelo** [comment]
@iphands Good to go now

**Pull request merged**
