### PR TITLE
Master to master-stable

### PR DESCRIPTION
**Pull request by InsaneZein**
moving https://github.com/RedHatInsights/insights-chrome/pull/2014 to master-stable

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@InsaneZein this does seems right, there should be way more commits

**Comment by Hyperkid123** [comment]
@InsaneZein maybe your master-stable branch is not up to date? If yo ran cherry pick you should only get the one commit. Nothing else.

**Comment by InsaneZein** [comment]
I will close this and open a new one after I make sure master-stable is up to date.

**Comment by Hyperkid123** [comment]
@InsaneZein I see. That is the merge commit. You should cherry pick this one: https://github.com/RedHatInsights/insights-chrome/commit/1db320c68e68851c1afa501f7736c5cf572be430

```
1db320c68e68851c1afa501f7736c5cf572be430
```

**Comment by Hyperkid123** [comment]
Also the target branch is `master` not `master-stable`

**Pull request closed without merging**
